version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container

    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    restart: always
volumes:
  mysql_data:

networks:
  my_network:
